//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SCI.Idioma.IRKO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.irko.com.br")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Resultado))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CampoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarIdiomasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarIdiomasHabilitadosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::SCI.Properties.Settings.Default.SCI_Idioma_IRKO_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CampoCompletedEventHandler CampoCompleted;
        
        /// <remarks/>
        public event ListarIdiomasCompletedEventHandler ListarIdiomasCompleted;
        
        /// <remarks/>
        public event ListarIdiomasHabilitadosCompletedEventHandler ListarIdiomasHabilitadosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/ADM.WebService.Idioma.Campo", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoCampo Campo(string Guid, [System.Xml.Serialization.XmlElementAttribute("Campo")] string Campo1, string CodigoIdioma) {
            object[] results = this.Invoke("Campo", new object[] {
                        Guid,
                        Campo1,
                        CodigoIdioma});
            return ((ResultadoCampo)(results[0]));
        }
        
        /// <remarks/>
        public void CampoAsync(string Guid, string Campo1, string CodigoIdioma) {
            this.CampoAsync(Guid, Campo1, CodigoIdioma, null);
        }
        
        /// <remarks/>
        public void CampoAsync(string Guid, string Campo1, string CodigoIdioma, object userState) {
            if ((this.CampoOperationCompleted == null)) {
                this.CampoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCampoOperationCompleted);
            }
            this.InvokeAsync("Campo", new object[] {
                        Guid,
                        Campo1,
                        CodigoIdioma}, this.CampoOperationCompleted, userState);
        }
        
        private void OnCampoOperationCompleted(object arg) {
            if ((this.CampoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CampoCompleted(this, new CampoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/ADM.WebService.Idioma.ListarIdiomas", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoListarIdioma ListarIdiomas(string Guid) {
            object[] results = this.Invoke("ListarIdiomas", new object[] {
                        Guid});
            return ((ResultadoListarIdioma)(results[0]));
        }
        
        /// <remarks/>
        public void ListarIdiomasAsync(string Guid) {
            this.ListarIdiomasAsync(Guid, null);
        }
        
        /// <remarks/>
        public void ListarIdiomasAsync(string Guid, object userState) {
            if ((this.ListarIdiomasOperationCompleted == null)) {
                this.ListarIdiomasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarIdiomasOperationCompleted);
            }
            this.InvokeAsync("ListarIdiomas", new object[] {
                        Guid}, this.ListarIdiomasOperationCompleted, userState);
        }
        
        private void OnListarIdiomasOperationCompleted(object arg) {
            if ((this.ListarIdiomasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarIdiomasCompleted(this, new ListarIdiomasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/ADM.WebService.Idioma.ListarIdiomasHabilitados", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoListarIdioma ListarIdiomasHabilitados(string Guid) {
            object[] results = this.Invoke("ListarIdiomasHabilitados", new object[] {
                        Guid});
            return ((ResultadoListarIdioma)(results[0]));
        }
        
        /// <remarks/>
        public void ListarIdiomasHabilitadosAsync(string Guid) {
            this.ListarIdiomasHabilitadosAsync(Guid, null);
        }
        
        /// <remarks/>
        public void ListarIdiomasHabilitadosAsync(string Guid, object userState) {
            if ((this.ListarIdiomasHabilitadosOperationCompleted == null)) {
                this.ListarIdiomasHabilitadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarIdiomasHabilitadosOperationCompleted);
            }
            this.InvokeAsync("ListarIdiomasHabilitados", new object[] {
                        Guid}, this.ListarIdiomasHabilitadosOperationCompleted, userState);
        }
        
        private void OnListarIdiomasHabilitadosOperationCompleted(object arg) {
            if ((this.ListarIdiomasHabilitadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarIdiomasHabilitadosCompleted(this, new ListarIdiomasHabilitadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoCampo : Resultado {
        
        private string retornoCampoField;
        
        /// <remarks/>
        public string RetornoCampo {
            get {
                return this.retornoCampoField;
            }
            set {
                this.retornoCampoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoListarIdioma))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoCampo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Resultado {
        
        private bool sucessoField;
        
        private bool sucessoFieldSpecified;
        
        private string mensagemField;
        
        private string divisorLinhaField;
        
        private string tagField;
        
        /// <remarks/>
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SucessoSpecified {
            get {
                return this.sucessoFieldSpecified;
            }
            set {
                this.sucessoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public string DivisorLinha {
            get {
                return this.divisorLinhaField;
            }
            set {
                this.divisorLinhaField = value;
            }
        }
        
        /// <remarks/>
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Idioma {
        
        private string codigoField;
        
        private string descricaoField;
        
        private bool habilitadoField;
        
        private bool habilitadoFieldSpecified;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public bool Habilitado {
            get {
                return this.habilitadoField;
            }
            set {
                this.habilitadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HabilitadoSpecified {
            get {
                return this.habilitadoFieldSpecified;
            }
            set {
                this.habilitadoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoListarIdioma : Resultado {
        
        private Idioma[] retornoListarIdiomaField;
        
        /// <remarks/>
        public Idioma[] RetornoListarIdioma {
            get {
                return this.retornoListarIdiomaField;
            }
            set {
                this.retornoListarIdiomaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CampoCompletedEventHandler(object sender, CampoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CampoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CampoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoCampo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoCampo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarIdiomasCompletedEventHandler(object sender, ListarIdiomasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarIdiomasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarIdiomasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoListarIdioma Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoListarIdioma)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarIdiomasHabilitadosCompletedEventHandler(object sender, ListarIdiomasHabilitadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarIdiomasHabilitadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarIdiomasHabilitadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoListarIdioma Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoListarIdioma)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591