//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SCI.Sistema.IRKO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.irko.com.br")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Resultado))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListarLockOperationCompleted;
        
        private System.Threading.SendOrPostCallback PainelOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::SCI.Properties.Settings.Default.SCI_Sistema_IRKO_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListarLockCompletedEventHandler ListarLockCompleted;
        
        /// <remarks/>
        public event PainelCompletedEventHandler PainelCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/ADM.WebService.Sistema.ListarLock", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Lock[] ListarLock(string Guid) {
            object[] results = this.Invoke("ListarLock", new object[] {
                        Guid});
            return ((Lock[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarLockAsync(string Guid) {
            this.ListarLockAsync(Guid, null);
        }
        
        /// <remarks/>
        public void ListarLockAsync(string Guid, object userState) {
            if ((this.ListarLockOperationCompleted == null)) {
                this.ListarLockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarLockOperationCompleted);
            }
            this.InvokeAsync("ListarLock", new object[] {
                        Guid}, this.ListarLockOperationCompleted, userState);
        }
        
        private void OnListarLockOperationCompleted(object arg) {
            if ((this.ListarLockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarLockCompleted(this, new ListarLockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/ADM.WebService.Sistema.Painel", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoPainel Painel(string Guid) {
            object[] results = this.Invoke("Painel", new object[] {
                        Guid});
            return ((ResultadoPainel)(results[0]));
        }
        
        /// <remarks/>
        public void PainelAsync(string Guid) {
            this.PainelAsync(Guid, null);
        }
        
        /// <remarks/>
        public void PainelAsync(string Guid, object userState) {
            if ((this.PainelOperationCompleted == null)) {
                this.PainelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPainelOperationCompleted);
            }
            this.InvokeAsync("Painel", new object[] {
                        Guid}, this.PainelOperationCompleted, userState);
        }
        
        private void OnPainelOperationCompleted(object arg) {
            if ((this.PainelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PainelCompleted(this, new PainelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Lock {
        
        private string delKeyField;
        
        private string ownerField;
        
        private string modeField;
        
        private string flagsField;
        
        private string countsField;
        
        private long sfnField;
        
        private bool sfnFieldSpecified;
        
        private string lockStringField;
        
        private string fullReferenceField;
        
        private string waiterPIDField;
        
        private string waiterModeField;
        
        private string waiterTypeField;
        
        private bool remoteOwnerField;
        
        private bool remoteOwnerFieldSpecified;
        
        private string escalateInfoField;
        
        /// <remarks/>
        public string DelKey {
            get {
                return this.delKeyField;
            }
            set {
                this.delKeyField = value;
            }
        }
        
        /// <remarks/>
        public string Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        public string Flags {
            get {
                return this.flagsField;
            }
            set {
                this.flagsField = value;
            }
        }
        
        /// <remarks/>
        public string Counts {
            get {
                return this.countsField;
            }
            set {
                this.countsField = value;
            }
        }
        
        /// <remarks/>
        public long Sfn {
            get {
                return this.sfnField;
            }
            set {
                this.sfnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SfnSpecified {
            get {
                return this.sfnFieldSpecified;
            }
            set {
                this.sfnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string LockString {
            get {
                return this.lockStringField;
            }
            set {
                this.lockStringField = value;
            }
        }
        
        /// <remarks/>
        public string FullReference {
            get {
                return this.fullReferenceField;
            }
            set {
                this.fullReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string WaiterPID {
            get {
                return this.waiterPIDField;
            }
            set {
                this.waiterPIDField = value;
            }
        }
        
        /// <remarks/>
        public string WaiterMode {
            get {
                return this.waiterModeField;
            }
            set {
                this.waiterModeField = value;
            }
        }
        
        /// <remarks/>
        public string WaiterType {
            get {
                return this.waiterTypeField;
            }
            set {
                this.waiterTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool RemoteOwner {
            get {
                return this.remoteOwnerField;
            }
            set {
                this.remoteOwnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RemoteOwnerSpecified {
            get {
                return this.remoteOwnerFieldSpecified;
            }
            set {
                this.remoteOwnerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EscalateInfo {
            get {
                return this.escalateInfoField;
            }
            set {
                this.escalateInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Chamado {
        
        private string aNOMESField;
        
        private string nomeField;
        
        private string totalChamadoField;
        
        private string fechadoField;
        
        private string naoProcedeField;
        
        private string pendenteField;
        
        /// <remarks/>
        public string ANOMES {
            get {
                return this.aNOMESField;
            }
            set {
                this.aNOMESField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string TotalChamado {
            get {
                return this.totalChamadoField;
            }
            set {
                this.totalChamadoField = value;
            }
        }
        
        /// <remarks/>
        public string Fechado {
            get {
                return this.fechadoField;
            }
            set {
                this.fechadoField = value;
            }
        }
        
        /// <remarks/>
        public string NaoProcede {
            get {
                return this.naoProcedeField;
            }
            set {
                this.naoProcedeField = value;
            }
        }
        
        /// <remarks/>
        public string Pendente {
            get {
                return this.pendenteField;
            }
            set {
                this.pendenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class PairOfRotinaSistemaIrkoKeyLong {
        
        private string rotinaSistemaIrkoKeyField;
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RotinaSistemaIrkoKey {
            get {
                return this.rotinaSistemaIrkoKeyField;
            }
            set {
                this.rotinaSistemaIrkoKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public long Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Painel {
        
        private long totalLincencaField;
        
        private bool totalLincencaFieldSpecified;
        
        private long usoAtualLicencaField;
        
        private bool usoAtualLicencaFieldSpecified;
        
        private long totalLogadoIrkoField;
        
        private bool totalLogadoIrkoFieldSpecified;
        
        private PairOfRotinaSistemaIrkoKeyLong[] rotinaSistemaIrkoField;
        
        private long tamanhoLockField;
        
        private bool tamanhoLockFieldSpecified;
        
        private long usoLockField;
        
        private bool usoLockFieldSpecified;
        
        private long lockLivreField;
        
        private bool lockLivreFieldSpecified;
        
        private long lockSistemaField;
        
        private bool lockSistemaFieldSpecified;
        
        private long workUsadoField;
        
        private bool workUsadoFieldSpecified;
        
        private Chamado[] chamadosField;
        
        /// <remarks/>
        public long TotalLincenca {
            get {
                return this.totalLincencaField;
            }
            set {
                this.totalLincencaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalLincencaSpecified {
            get {
                return this.totalLincencaFieldSpecified;
            }
            set {
                this.totalLincencaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long UsoAtualLicenca {
            get {
                return this.usoAtualLicencaField;
            }
            set {
                this.usoAtualLicencaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UsoAtualLicencaSpecified {
            get {
                return this.usoAtualLicencaFieldSpecified;
            }
            set {
                this.usoAtualLicencaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long TotalLogadoIrko {
            get {
                return this.totalLogadoIrkoField;
            }
            set {
                this.totalLogadoIrkoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalLogadoIrkoSpecified {
            get {
                return this.totalLogadoIrkoFieldSpecified;
            }
            set {
                this.totalLogadoIrkoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RotinaSistemaIrkoItem")]
        public PairOfRotinaSistemaIrkoKeyLong[] RotinaSistemaIrko {
            get {
                return this.rotinaSistemaIrkoField;
            }
            set {
                this.rotinaSistemaIrkoField = value;
            }
        }
        
        /// <remarks/>
        public long TamanhoLock {
            get {
                return this.tamanhoLockField;
            }
            set {
                this.tamanhoLockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TamanhoLockSpecified {
            get {
                return this.tamanhoLockFieldSpecified;
            }
            set {
                this.tamanhoLockFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long UsoLock {
            get {
                return this.usoLockField;
            }
            set {
                this.usoLockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UsoLockSpecified {
            get {
                return this.usoLockFieldSpecified;
            }
            set {
                this.usoLockFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long LockLivre {
            get {
                return this.lockLivreField;
            }
            set {
                this.lockLivreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LockLivreSpecified {
            get {
                return this.lockLivreFieldSpecified;
            }
            set {
                this.lockLivreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long LockSistema {
            get {
                return this.lockSistemaField;
            }
            set {
                this.lockSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LockSistemaSpecified {
            get {
                return this.lockSistemaFieldSpecified;
            }
            set {
                this.lockSistemaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long WorkUsado {
            get {
                return this.workUsadoField;
            }
            set {
                this.workUsadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WorkUsadoSpecified {
            get {
                return this.workUsadoFieldSpecified;
            }
            set {
                this.workUsadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Chamado[] Chamados {
            get {
                return this.chamadosField;
            }
            set {
                this.chamadosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoPainel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Resultado {
        
        private bool sucessoField;
        
        private bool sucessoFieldSpecified;
        
        private string mensagemField;
        
        private string divisorLinhaField;
        
        private string tagField;
        
        /// <remarks/>
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SucessoSpecified {
            get {
                return this.sucessoFieldSpecified;
            }
            set {
                this.sucessoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public string DivisorLinha {
            get {
                return this.divisorLinhaField;
            }
            set {
                this.divisorLinhaField = value;
            }
        }
        
        /// <remarks/>
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoPainel : Resultado {
        
        private Painel retornoPainelField;
        
        /// <remarks/>
        public Painel RetornoPainel {
            get {
                return this.retornoPainelField;
            }
            set {
                this.retornoPainelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarLockCompletedEventHandler(object sender, ListarLockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarLockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarLockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Lock[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Lock[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void PainelCompletedEventHandler(object sender, PainelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PainelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PainelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoPainel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoPainel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591