//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SCI.Trabalhista {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AcessoTrabalhistaSoap", Namespace="http://www.irko.com.br")]
    public partial class AcessoTrabalhista : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CalcularFolhaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirVerbaOperationCompleted;
        
        private System.Threading.SendOrPostCallback FolhaCentroCustoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GravarVerbaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarFuncionarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarVerbaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarVerbaCadastradaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarParametroOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AcessoTrabalhista() {
            this.Url = global::SCI.Properties.Settings.Default.SCI_Trabalhista_AcessoTrabalhista;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CalcularFolhaCompletedEventHandler CalcularFolhaCompleted;
        
        /// <remarks/>
        public event ExcluirVerbaCompletedEventHandler ExcluirVerbaCompleted;
        
        /// <remarks/>
        public event FolhaCentroCustoCompletedEventHandler FolhaCentroCustoCompleted;
        
        /// <remarks/>
        public event GravarVerbaCompletedEventHandler GravarVerbaCompleted;
        
        /// <remarks/>
        public event ListarFuncionarioCompletedEventHandler ListarFuncionarioCompleted;
        
        /// <remarks/>
        public event ListarVerbaCompletedEventHandler ListarVerbaCompleted;
        
        /// <remarks/>
        public event ListarVerbaCadastradaCompletedEventHandler ListarVerbaCadastradaCompleted;
        
        /// <remarks/>
        public event RecuperarParametroCompletedEventHandler RecuperarParametroCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/WebService.Trabalhista.CalcularFolha", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resultado CalcularFolha(string Guid, string ANOMES, string CodigoFuncionario, string TipoRegistro) {
            object[] results = this.Invoke("CalcularFolha", new object[] {
                        Guid,
                        ANOMES,
                        CodigoFuncionario,
                        TipoRegistro});
            return ((Resultado)(results[0]));
        }
        
        /// <remarks/>
        public void CalcularFolhaAsync(string Guid, string ANOMES, string CodigoFuncionario, string TipoRegistro) {
            this.CalcularFolhaAsync(Guid, ANOMES, CodigoFuncionario, TipoRegistro, null);
        }
        
        /// <remarks/>
        public void CalcularFolhaAsync(string Guid, string ANOMES, string CodigoFuncionario, string TipoRegistro, object userState) {
            if ((this.CalcularFolhaOperationCompleted == null)) {
                this.CalcularFolhaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalcularFolhaOperationCompleted);
            }
            this.InvokeAsync("CalcularFolha", new object[] {
                        Guid,
                        ANOMES,
                        CodigoFuncionario,
                        TipoRegistro}, this.CalcularFolhaOperationCompleted, userState);
        }
        
        private void OnCalcularFolhaOperationCompleted(object arg) {
            if ((this.CalcularFolhaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalcularFolhaCompleted(this, new CalcularFolhaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/WebService.Trabalhista.ExcluirVerba", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resultado ExcluirVerba(string Guid, string ANOMES, string CodigoFuncionario, string TipoRegistro, string TipoVerba, string CodigoVerba) {
            object[] results = this.Invoke("ExcluirVerba", new object[] {
                        Guid,
                        ANOMES,
                        CodigoFuncionario,
                        TipoRegistro,
                        TipoVerba,
                        CodigoVerba});
            return ((Resultado)(results[0]));
        }
        
        /// <remarks/>
        public void ExcluirVerbaAsync(string Guid, string ANOMES, string CodigoFuncionario, string TipoRegistro, string TipoVerba, string CodigoVerba) {
            this.ExcluirVerbaAsync(Guid, ANOMES, CodigoFuncionario, TipoRegistro, TipoVerba, CodigoVerba, null);
        }
        
        /// <remarks/>
        public void ExcluirVerbaAsync(string Guid, string ANOMES, string CodigoFuncionario, string TipoRegistro, string TipoVerba, string CodigoVerba, object userState) {
            if ((this.ExcluirVerbaOperationCompleted == null)) {
                this.ExcluirVerbaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirVerbaOperationCompleted);
            }
            this.InvokeAsync("ExcluirVerba", new object[] {
                        Guid,
                        ANOMES,
                        CodigoFuncionario,
                        TipoRegistro,
                        TipoVerba,
                        CodigoVerba}, this.ExcluirVerbaOperationCompleted, userState);
        }
        
        private void OnExcluirVerbaOperationCompleted(object arg) {
            if ((this.ExcluirVerbaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirVerbaCompleted(this, new ExcluirVerbaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/WebService.Trabalhista.FolhaCentroCusto", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoListarVerbaCadastrada FolhaCentroCusto(string Guid, string ANOMES, string TipoRegistro, string CodigoCentroCusto, string CodigoFuncionario) {
            object[] results = this.Invoke("FolhaCentroCusto", new object[] {
                        Guid,
                        ANOMES,
                        TipoRegistro,
                        CodigoCentroCusto,
                        CodigoFuncionario});
            return ((ResultadoListarVerbaCadastrada)(results[0]));
        }
        
        /// <remarks/>
        public void FolhaCentroCustoAsync(string Guid, string ANOMES, string TipoRegistro, string CodigoCentroCusto, string CodigoFuncionario) {
            this.FolhaCentroCustoAsync(Guid, ANOMES, TipoRegistro, CodigoCentroCusto, CodigoFuncionario, null);
        }
        
        /// <remarks/>
        public void FolhaCentroCustoAsync(string Guid, string ANOMES, string TipoRegistro, string CodigoCentroCusto, string CodigoFuncionario, object userState) {
            if ((this.FolhaCentroCustoOperationCompleted == null)) {
                this.FolhaCentroCustoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFolhaCentroCustoOperationCompleted);
            }
            this.InvokeAsync("FolhaCentroCusto", new object[] {
                        Guid,
                        ANOMES,
                        TipoRegistro,
                        CodigoCentroCusto,
                        CodigoFuncionario}, this.FolhaCentroCustoOperationCompleted, userState);
        }
        
        private void OnFolhaCentroCustoOperationCompleted(object arg) {
            if ((this.FolhaCentroCustoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FolhaCentroCustoCompleted(this, new FolhaCentroCustoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/WebService.Trabalhista.GravarVerba", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resultado GravarVerba(string Guid, string ANOMES, string CodigoFuncionario, string TipoRegistro, string TipoVerba, string CodigoVerba, string Quantidade, string Valor) {
            object[] results = this.Invoke("GravarVerba", new object[] {
                        Guid,
                        ANOMES,
                        CodigoFuncionario,
                        TipoRegistro,
                        TipoVerba,
                        CodigoVerba,
                        Quantidade,
                        Valor});
            return ((Resultado)(results[0]));
        }
        
        /// <remarks/>
        public void GravarVerbaAsync(string Guid, string ANOMES, string CodigoFuncionario, string TipoRegistro, string TipoVerba, string CodigoVerba, string Quantidade, string Valor) {
            this.GravarVerbaAsync(Guid, ANOMES, CodigoFuncionario, TipoRegistro, TipoVerba, CodigoVerba, Quantidade, Valor, null);
        }
        
        /// <remarks/>
        public void GravarVerbaAsync(string Guid, string ANOMES, string CodigoFuncionario, string TipoRegistro, string TipoVerba, string CodigoVerba, string Quantidade, string Valor, object userState) {
            if ((this.GravarVerbaOperationCompleted == null)) {
                this.GravarVerbaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGravarVerbaOperationCompleted);
            }
            this.InvokeAsync("GravarVerba", new object[] {
                        Guid,
                        ANOMES,
                        CodigoFuncionario,
                        TipoRegistro,
                        TipoVerba,
                        CodigoVerba,
                        Quantidade,
                        Valor}, this.GravarVerbaOperationCompleted, userState);
        }
        
        private void OnGravarVerbaOperationCompleted(object arg) {
            if ((this.GravarVerbaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GravarVerbaCompleted(this, new GravarVerbaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/WebService.Trabalhista.ListarFuncionario", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoListarFuncionario ListarFuncionario(string Guid) {
            object[] results = this.Invoke("ListarFuncionario", new object[] {
                        Guid});
            return ((ResultadoListarFuncionario)(results[0]));
        }
        
        /// <remarks/>
        public void ListarFuncionarioAsync(string Guid) {
            this.ListarFuncionarioAsync(Guid, null);
        }
        
        /// <remarks/>
        public void ListarFuncionarioAsync(string Guid, object userState) {
            if ((this.ListarFuncionarioOperationCompleted == null)) {
                this.ListarFuncionarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarFuncionarioOperationCompleted);
            }
            this.InvokeAsync("ListarFuncionario", new object[] {
                        Guid}, this.ListarFuncionarioOperationCompleted, userState);
        }
        
        private void OnListarFuncionarioOperationCompleted(object arg) {
            if ((this.ListarFuncionarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarFuncionarioCompleted(this, new ListarFuncionarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/WebService.Trabalhista.ListarVerba", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoListarVerba ListarVerba(string Guid) {
            object[] results = this.Invoke("ListarVerba", new object[] {
                        Guid});
            return ((ResultadoListarVerba)(results[0]));
        }
        
        /// <remarks/>
        public void ListarVerbaAsync(string Guid) {
            this.ListarVerbaAsync(Guid, null);
        }
        
        /// <remarks/>
        public void ListarVerbaAsync(string Guid, object userState) {
            if ((this.ListarVerbaOperationCompleted == null)) {
                this.ListarVerbaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarVerbaOperationCompleted);
            }
            this.InvokeAsync("ListarVerba", new object[] {
                        Guid}, this.ListarVerbaOperationCompleted, userState);
        }
        
        private void OnListarVerbaOperationCompleted(object arg) {
            if ((this.ListarVerbaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarVerbaCompleted(this, new ListarVerbaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/WebService.Trabalhista.ListarVerbaCadastrada", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoListarVerbaCadastrada ListarVerbaCadastrada(string Guid, string ANOMES, string CodigoFuncionario) {
            object[] results = this.Invoke("ListarVerbaCadastrada", new object[] {
                        Guid,
                        ANOMES,
                        CodigoFuncionario});
            return ((ResultadoListarVerbaCadastrada)(results[0]));
        }
        
        /// <remarks/>
        public void ListarVerbaCadastradaAsync(string Guid, string ANOMES, string CodigoFuncionario) {
            this.ListarVerbaCadastradaAsync(Guid, ANOMES, CodigoFuncionario, null);
        }
        
        /// <remarks/>
        public void ListarVerbaCadastradaAsync(string Guid, string ANOMES, string CodigoFuncionario, object userState) {
            if ((this.ListarVerbaCadastradaOperationCompleted == null)) {
                this.ListarVerbaCadastradaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarVerbaCadastradaOperationCompleted);
            }
            this.InvokeAsync("ListarVerbaCadastrada", new object[] {
                        Guid,
                        ANOMES,
                        CodigoFuncionario}, this.ListarVerbaCadastradaOperationCompleted, userState);
        }
        
        private void OnListarVerbaCadastradaOperationCompleted(object arg) {
            if ((this.ListarVerbaCadastradaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarVerbaCadastradaCompleted(this, new ListarVerbaCadastradaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/WebService.Trabalhista.RecuperarParametro", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoRecuperarParametro RecuperarParametro(string Guid) {
            object[] results = this.Invoke("RecuperarParametro", new object[] {
                        Guid});
            return ((ResultadoRecuperarParametro)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarParametroAsync(string Guid) {
            this.RecuperarParametroAsync(Guid, null);
        }
        
        /// <remarks/>
        public void RecuperarParametroAsync(string Guid, object userState) {
            if ((this.RecuperarParametroOperationCompleted == null)) {
                this.RecuperarParametroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarParametroOperationCompleted);
            }
            this.InvokeAsync("RecuperarParametro", new object[] {
                        Guid}, this.RecuperarParametroOperationCompleted, userState);
        }
        
        private void OnRecuperarParametroOperationCompleted(object arg) {
            if ((this.RecuperarParametroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarParametroCompleted(this, new RecuperarParametroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoRecuperarParametro))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoListarVerbaCadastrada))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoListarVerba))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoListarFuncionario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoListarIdioma))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoListarEmpresa))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoMontarMenu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoLogin))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Resultado {
        
        private bool sucessoField;
        
        private bool sucessoFieldSpecified;
        
        private string mensagemField;
        
        private string divisorLinhaField;
        
        private string tagField;
        
        private Stack[] stacksField;
        
        /// <remarks/>
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SucessoSpecified {
            get {
                return this.sucessoFieldSpecified;
            }
            set {
                this.sucessoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public string DivisorLinha {
            get {
                return this.divisorLinhaField;
            }
            set {
                this.divisorLinhaField = value;
            }
        }
        
        /// <remarks/>
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
        
        /// <remarks/>
        public Stack[] Stacks {
            get {
                return this.stacksField;
            }
            set {
                this.stacksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Stack {
        
        private long levelField;
        
        private bool levelFieldSpecified;
        
        private string placeField;
        
        private string mCodeField;
        
        private string eCodeField;
        
        /// <remarks/>
        public long Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LevelSpecified {
            get {
                return this.levelFieldSpecified;
            }
            set {
                this.levelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
            }
        }
        
        /// <remarks/>
        public string MCode {
            get {
                return this.mCodeField;
            }
            set {
                this.mCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ECode {
            get {
                return this.eCodeField;
            }
            set {
                this.eCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Registro {
        
        private Funcionario funcionarioField;
        
        private string competenciaField;
        
        private RegistroTipo tipoField;
        
        private bool tipoFieldSpecified;
        
        private RegistroFixa fixaField;
        
        private bool fixaFieldSpecified;
        
        private string tipoProventoField;
        
        private Verba verbaField;
        
        private decimal quantidadeField;
        
        private bool quantidadeFieldSpecified;
        
        private decimal valorField;
        
        private bool valorFieldSpecified;
        
        /// <remarks/>
        public Funcionario Funcionario {
            get {
                return this.funcionarioField;
            }
            set {
                this.funcionarioField = value;
            }
        }
        
        /// <remarks/>
        public string Competencia {
            get {
                return this.competenciaField;
            }
            set {
                this.competenciaField = value;
            }
        }
        
        /// <remarks/>
        public RegistroTipo Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public RegistroFixa Fixa {
            get {
                return this.fixaField;
            }
            set {
                this.fixaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FixaSpecified {
            get {
                return this.fixaFieldSpecified;
            }
            set {
                this.fixaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string TipoProvento {
            get {
                return this.tipoProventoField;
            }
            set {
                this.tipoProventoField = value;
            }
        }
        
        /// <remarks/>
        public Verba Verba {
            get {
                return this.verbaField;
            }
            set {
                this.verbaField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantidadeSpecified {
            get {
                return this.quantidadeFieldSpecified;
            }
            set {
                this.quantidadeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorSpecified {
            get {
                return this.valorFieldSpecified;
            }
            set {
                this.valorFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Funcionario {
        
        private long codigoField;
        
        private string nomeField;
        
        private Departamento departamentoField;
        
        private CentroCusto centroCustoField;
        
        private bool ativoField;
        
        private bool ativoFieldSpecified;
        
        private System.DateTime admissaoField;
        
        private bool admissaoFieldSpecified;
        
        /// <remarks/>
        public long Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public Departamento Departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
            }
        }
        
        /// <remarks/>
        public CentroCusto CentroCusto {
            get {
                return this.centroCustoField;
            }
            set {
                this.centroCustoField = value;
            }
        }
        
        /// <remarks/>
        public bool Ativo {
            get {
                return this.ativoField;
            }
            set {
                this.ativoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AtivoSpecified {
            get {
                return this.ativoFieldSpecified;
            }
            set {
                this.ativoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Admissao {
            get {
                return this.admissaoField;
            }
            set {
                this.admissaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdmissaoSpecified {
            get {
                return this.admissaoFieldSpecified;
            }
            set {
                this.admissaoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Departamento {
        
        private long codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descricaoField;
        
        /// <remarks/>
        public long Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class CentroCusto {
        
        private string codigoField;
        
        private string descricaoField;
        
        private string grupoField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public string Grupo {
            get {
                return this.grupoField;
            }
            set {
                this.grupoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.irko.com.br")]
    public enum RegistroTipo {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("300")]
        Item300,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("550")]
        Item550,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("450")]
        Item450,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("620")]
        Item620,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("650")]
        Item650,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("680")]
        Item680,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.irko.com.br")]
    public enum RegistroFixa {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Verba {
        
        private long codigoField;
        
        private string descricaoField;
        
        private bool ativaField;
        
        private bool ativaFieldSpecified;
        
        /// <remarks/>
        public long Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public bool Ativa {
            get {
                return this.ativaField;
            }
            set {
                this.ativaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AtivaSpecified {
            get {
                return this.ativaFieldSpecified;
            }
            set {
                this.ativaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Idioma {
        
        private string codigoField;
        
        private string descricaoField;
        
        private bool habilitadoField;
        
        private bool habilitadoFieldSpecified;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public bool Habilitado {
            get {
                return this.habilitadoField;
            }
            set {
                this.habilitadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HabilitadoSpecified {
            get {
                return this.habilitadoFieldSpecified;
            }
            set {
                this.habilitadoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Empresa {
        
        private long codigoField;
        
        private string razaoSocialField;
        
        private string cNPJCPFField;
        
        private EmpresaStatus statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        public long Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string RazaoSocial {
            get {
                return this.razaoSocialField;
            }
            set {
                this.razaoSocialField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJCPF {
            get {
                return this.cNPJCPFField;
            }
            set {
                this.cNPJCPFField = value;
            }
        }
        
        /// <remarks/>
        public EmpresaStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.irko.com.br")]
    public enum EmpresaStatus {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Menu {
        
        private Menu[] menusInferioresField;
        
        private string menu1Field;
        
        private string descricaoField;
        
        private MenuTipo tipoField;
        
        private MenuStatus statusField;
        
        private string namespaceField;
        
        private string programaField;
        
        private MenuBloqueio bloqueioField;
        
        private bool bloqueioFieldSpecified;
        
        private bool permiteTrocaEmpresaField;
        
        private bool permiteTrocaEmpresaFieldSpecified;
        
        private bool permiteMultiTelaField;
        
        private bool permiteMultiTelaFieldSpecified;
        
        private string opcaoMenuCOSField;
        
        private bool permiteEditarField;
        
        private bool permiteEditarFieldSpecified;
        
        /// <remarks/>
        public Menu[] MenusInferiores {
            get {
                return this.menusInferioresField;
            }
            set {
                this.menusInferioresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Menu")]
        public string Menu1 {
            get {
                return this.menu1Field;
            }
            set {
                this.menu1Field = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public MenuTipo Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public MenuStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        public string Programa {
            get {
                return this.programaField;
            }
            set {
                this.programaField = value;
            }
        }
        
        /// <remarks/>
        public MenuBloqueio Bloqueio {
            get {
                return this.bloqueioField;
            }
            set {
                this.bloqueioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BloqueioSpecified {
            get {
                return this.bloqueioFieldSpecified;
            }
            set {
                this.bloqueioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool PermiteTrocaEmpresa {
            get {
                return this.permiteTrocaEmpresaField;
            }
            set {
                this.permiteTrocaEmpresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PermiteTrocaEmpresaSpecified {
            get {
                return this.permiteTrocaEmpresaFieldSpecified;
            }
            set {
                this.permiteTrocaEmpresaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool PermiteMultiTela {
            get {
                return this.permiteMultiTelaField;
            }
            set {
                this.permiteMultiTelaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PermiteMultiTelaSpecified {
            get {
                return this.permiteMultiTelaFieldSpecified;
            }
            set {
                this.permiteMultiTelaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string OpcaoMenuCOS {
            get {
                return this.opcaoMenuCOSField;
            }
            set {
                this.opcaoMenuCOSField = value;
            }
        }
        
        /// <remarks/>
        public bool PermiteEditar {
            get {
                return this.permiteEditarField;
            }
            set {
                this.permiteEditarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PermiteEditarSpecified {
            get {
                return this.permiteEditarFieldSpecified;
            }
            set {
                this.permiteEditarFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.irko.com.br")]
    public enum MenuTipo {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.irko.com.br")]
    public enum MenuStatus {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.irko.com.br")]
    public enum MenuBloqueio {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Usuario {
        
        private long codigoField;
        
        private string nomeField;
        
        private string senhaField;
        
        private UsuarioStatus statusField;
        
        private System.DateTime dataInicioField;
        
        /// <remarks/>
        public long Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public UsuarioStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataInicio {
            get {
                return this.dataInicioField;
            }
            set {
                this.dataInicioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.irko.com.br")]
    public enum UsuarioStatus {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoRecuperarParametro : Resultado {
        
        private string anoMesAtualField;
        
        private Verba verbaSalarioField;
        
        /// <remarks/>
        public string AnoMesAtual {
            get {
                return this.anoMesAtualField;
            }
            set {
                this.anoMesAtualField = value;
            }
        }
        
        /// <remarks/>
        public Verba VerbaSalario {
            get {
                return this.verbaSalarioField;
            }
            set {
                this.verbaSalarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoListarVerbaCadastrada : Resultado {
        
        private Registro[] retornoListarVerbaCadastradaField;
        
        /// <remarks/>
        public Registro[] RetornoListarVerbaCadastrada {
            get {
                return this.retornoListarVerbaCadastradaField;
            }
            set {
                this.retornoListarVerbaCadastradaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoListarVerba : Resultado {
        
        private Verba[] retornoListarVerbaField;
        
        /// <remarks/>
        public Verba[] RetornoListarVerba {
            get {
                return this.retornoListarVerbaField;
            }
            set {
                this.retornoListarVerbaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoListarFuncionario : Resultado {
        
        private Funcionario[] retornoListarFuncionarioField;
        
        /// <remarks/>
        public Funcionario[] RetornoListarFuncionario {
            get {
                return this.retornoListarFuncionarioField;
            }
            set {
                this.retornoListarFuncionarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoListarIdioma : Resultado {
        
        private Idioma[] retornoListarIdiomaField;
        
        /// <remarks/>
        public Idioma[] RetornoListarIdioma {
            get {
                return this.retornoListarIdiomaField;
            }
            set {
                this.retornoListarIdiomaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoListarEmpresa : Resultado {
        
        private Empresa[] retornoListarEmpresaField;
        
        /// <remarks/>
        public Empresa[] RetornoListarEmpresa {
            get {
                return this.retornoListarEmpresaField;
            }
            set {
                this.retornoListarEmpresaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoMontarMenu : Resultado {
        
        private Menu[] retornoResultadoMontarMenuField;
        
        /// <remarks/>
        public Menu[] RetornoResultadoMontarMenu {
            get {
                return this.retornoResultadoMontarMenuField;
            }
            set {
                this.retornoResultadoMontarMenuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoLogin : Resultado {
        
        private Usuario retornoResultadoLoginField;
        
        /// <remarks/>
        public Usuario RetornoResultadoLogin {
            get {
                return this.retornoResultadoLoginField;
            }
            set {
                this.retornoResultadoLoginField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CalcularFolhaCompletedEventHandler(object sender, CalcularFolhaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalcularFolhaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalcularFolhaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ExcluirVerbaCompletedEventHandler(object sender, ExcluirVerbaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExcluirVerbaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExcluirVerbaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void FolhaCentroCustoCompletedEventHandler(object sender, FolhaCentroCustoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FolhaCentroCustoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FolhaCentroCustoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoListarVerbaCadastrada Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoListarVerbaCadastrada)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GravarVerbaCompletedEventHandler(object sender, GravarVerbaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GravarVerbaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GravarVerbaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ListarFuncionarioCompletedEventHandler(object sender, ListarFuncionarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarFuncionarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarFuncionarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoListarFuncionario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoListarFuncionario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ListarVerbaCompletedEventHandler(object sender, ListarVerbaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarVerbaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarVerbaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoListarVerba Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoListarVerba)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ListarVerbaCadastradaCompletedEventHandler(object sender, ListarVerbaCadastradaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarVerbaCadastradaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarVerbaCadastradaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoListarVerbaCadastrada Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoListarVerbaCadastrada)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void RecuperarParametroCompletedEventHandler(object sender, RecuperarParametroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarParametroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarParametroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoRecuperarParametro Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoRecuperarParametro)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591