//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.irko.com.br:443/csp/admsys/ADM.WebService.Acesso.cls")]
        public string SCI_Acesso_Acesso {
            get {
                return ((string)(this["SCI_Acesso_Acesso"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.irko.com.br:443/csp/admsys/ADM.WebService.Idioma.cls")]
        public string SCI_Idioma_Idioma {
            get {
                return ((string)(this["SCI_Idioma_Idioma"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.irko.com.br:443/csp/admsys/ADM.WebService.Corporativo.cls")]
        public string SCI_Corporativo_CorporativoService {
            get {
                return ((string)(this["SCI_Corporativo_CorporativoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://128.0.0.5:57773/csp/user/WebService.Trabalhista.cls")]
        public string SCI_Trabalhista_AcessoTrabalhista {
            get {
                return ((string)(this["SCI_Trabalhista_AcessoTrabalhista"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.irko.com.br:443/csp/admsys/WebService.IRKDesktop.cls")]
        public string SCI_IRKDesktop_GetData {
            get {
                return ((string)(this["SCI_IRKDesktop_GetData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://128.0.0.5:57773/csp/user/WebService.DCTF.cls")]
        public string SCI_DCTF_DCTFService {
            get {
                return ((string)(this["SCI_DCTF_DCTFService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.producaorestrita.esocial.gov.br/servicos/empregador/enviarlot" +
            "eeventos/WsEnviarLoteEventos.svc")]
        public string SCI_ESocial_ProducaoRestrita_ServicoEnviarLoteEventos {
            get {
                return ((string)(this["SCI_ESocial_ProducaoRestrita_ServicoEnviarLoteEventos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/cadconsultacadastro2.asmx")]
        public string SCI_teste_CadConsultaCadastro2 {
            get {
                return ((string)(this["SCI_teste_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.producaorestrita.esocial.gov.br/servicos/empregador/consultar" +
            "loteeventos/WsConsultarLoteEventos.svc")]
        public string SCI_ESocial_ProducaoRestrita_Retorno_ServicoConsultarLoteEventos {
            get {
                return ((string)(this["SCI_ESocial_ProducaoRestrita_Retorno_ServicoConsultarLoteEventos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.irko.com.br:443/csp/prgtrb/TRB.WebService.ESocial.cls")]
        public string SCI_ESocial_Service {
            get {
                return ((string)(this["SCI_ESocial_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://preprodefdreinf.receita.fazenda.gov.br/WsREINF/RecepcaoLoteReinf.svc")]
        public string SCI_Reinf_ProducaoRestrita_Envio_RecepcaoLoteReinf {
            get {
                return ((string)(this["SCI_Reinf_ProducaoRestrita_Envio_RecepcaoLoteReinf"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.irko.com.br:443/csp/prgdcn/DCN.WebService.Reinf.cls")]
        public string SCI_Reinf_Irko_Service {
            get {
                return ((string)(this["SCI_Reinf_Irko_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.envio.esocial.gov.br/servicos/empregador/enviarloteeventos/Ws" +
            "EnviarLoteEventos.svc")]
        public string SCI_ESocial_Producao_Envio_ServicoEnviarLoteEventos {
            get {
                return ((string)(this["SCI_ESocial_Producao_Envio_ServicoEnviarLoteEventos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.consulta.esocial.gov.br/servicos/empregador/consultarloteeven" +
            "tos/WsConsultarLoteEventos.svc")]
        public string SCI_ESocial_Producao_Retorno_ServicoConsultarLoteEventos {
            get {
                return ((string)(this["SCI_ESocial_Producao_Retorno_ServicoConsultarLoteEventos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.producaorestrita.esocial.gov.br/servicos/empregador/enviarlot" +
            "eeventos/WsEnviarLoteEventos.svc")]
        public string SCI_ESocial_ProducaoRestrita_Envio_ServicoEnviarLoteEventos {
            get {
                return ((string)(this["SCI_ESocial_ProducaoRestrita_Envio_ServicoEnviarLoteEventos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.irko.com.br:443/csp/prgtrb/TRB.WebService.ESocial.cls")]
        public string SCI_ESocial_IRKO_Service {
            get {
                return ((string)(this["SCI_ESocial_IRKO_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.irko.com.br:443/csp/prgdcn/DCN.WebService.ESocial.cls")]
        public string SCI_ESocial_IRKO_DCTF_Service {
            get {
                return ((string)(this["SCI_ESocial_IRKO_DCTF_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://preprodefdreinf.receita.fazenda.gov.br/WsREINFConsultas/ConsultasReinf.sv" +
            "c")]
        public string SCI_Reinf_ProducaoRestrita_Retorno_ConsultasReinf {
            get {
                return ((string)(this["SCI_Reinf_ProducaoRestrita_Retorno_ConsultasReinf"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://reinf.receita.fazenda.gov.br/WsREINF/RecepcaoLoteReinf.svc")]
        public string SCI_Reinf_Producao_Envio_RecepcaoLoteReinf {
            get {
                return ((string)(this["SCI_Reinf_Producao_Envio_RecepcaoLoteReinf"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://reinf.receita.fazenda.gov.br/WsREINFConsultas/ConsultasReinf.svc")]
        public string SCI_Reinf_Producao_Retorno_ConsultasReinf {
            get {
                return ((string)(this["SCI_Reinf_Producao_Retorno_ConsultasReinf"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://187.32.61.1:57772/csp/admsys/ADM.WebService.Acesso.cls")]
        public string SCI_Acesso_IRKOMPACTA_Service {
            get {
                return ((string)(this["SCI_Acesso_IRKOMPACTA_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://187.32.61.1:57772/csp/admsys/ADM.WebService.Corporativo.cls")]
        public string SCI_Corporativo_IRKOMPACTA_Service {
            get {
                return ((string)(this["SCI_Corporativo_IRKOMPACTA_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://187.32.61.1:57772/csp/admsys/ADM.WebService.Idioma.cls")]
        public string SCI_Idioma_IRKOMPACTA_Service {
            get {
                return ((string)(this["SCI_Idioma_IRKOMPACTA_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://187.32.61.1:57772/csp/admsys/ADM.WebService.Sistema.cls")]
        public string SCI_Sistema_IRKOMPACTA_Service {
            get {
                return ((string)(this["SCI_Sistema_IRKOMPACTA_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://187.32.61.1:57772/csp/prgtrb/TRB.WebService.ESocial.cls")]
        public string SCI_ESocial_IRKOMPACTA_Service {
            get {
                return ((string)(this["SCI_ESocial_IRKOMPACTA_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://187.32.61.1:57772/csp/prgdcn/DCN.WebService.ESocial.cls")]
        public string SCI_ESocial_IRKOMPACTA_DCTF_Service {
            get {
                return ((string)(this["SCI_ESocial_IRKOMPACTA_DCTF_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://187.32.61.1:57772/csp/prgdcn/DCN.WebService.Reinf.cls")]
        public string SCI_Reinf_IRKOMPACTA_Service {
            get {
                return ((string)(this["SCI_Reinf_IRKOMPACTA_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.irko.com.br:443/csp/admsys/ADM.WebService.Acesso.cls")]
        public string SCI_Acesso_IRKO_Service {
            get {
                return ((string)(this["SCI_Acesso_IRKO_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.irko.com.br:443/csp/admsys/ADM.WebService.Idioma.cls")]
        public string SCI_Idioma_IRKO_Service {
            get {
                return ((string)(this["SCI_Idioma_IRKO_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.irko.com.br:443/csp/admsys/ADM.WebService.Sistema.cls")]
        public string SCI_Sistema_IRKO_Service {
            get {
                return ((string)(this["SCI_Sistema_IRKO_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.irko.com.br:443/csp/admsys/ADM.WebService.Corporativo.cls")]
        public string SCI_Corporativo_IRKO_Service {
            get {
                return ((string)(this["SCI_Corporativo_IRKO_Service"]));
            }
        }
    }
}
