//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SCI.ESocial.IRKO.DCTF {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.irko.com.br")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Resultado))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GravarEnvioOperationCompleted;
        
        private System.Threading.SendOrPostCallback GravarRetornoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarEventoPendenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarRetornoPendenteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::SCI.Properties.Settings.Default.SCI_ESocial_IRKO_DCTF_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GravarEnvioCompletedEventHandler GravarEnvioCompleted;
        
        /// <remarks/>
        public event GravarRetornoCompletedEventHandler GravarRetornoCompleted;
        
        /// <remarks/>
        public event ListarEventoPendenteCompletedEventHandler ListarEventoPendenteCompleted;
        
        /// <remarks/>
        public event ListarRetornoPendenteCompletedEventHandler ListarRetornoPendenteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/DCN.WebService.ESocial.GravarEnvio", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoGravarEnvio GravarEnvio(string Guid, ParametroGravarEnvio ParametroGravarEnvio) {
            object[] results = this.Invoke("GravarEnvio", new object[] {
                        Guid,
                        ParametroGravarEnvio});
            return ((ResultadoGravarEnvio)(results[0]));
        }
        
        /// <remarks/>
        public void GravarEnvioAsync(string Guid, ParametroGravarEnvio ParametroGravarEnvio) {
            this.GravarEnvioAsync(Guid, ParametroGravarEnvio, null);
        }
        
        /// <remarks/>
        public void GravarEnvioAsync(string Guid, ParametroGravarEnvio ParametroGravarEnvio, object userState) {
            if ((this.GravarEnvioOperationCompleted == null)) {
                this.GravarEnvioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGravarEnvioOperationCompleted);
            }
            this.InvokeAsync("GravarEnvio", new object[] {
                        Guid,
                        ParametroGravarEnvio}, this.GravarEnvioOperationCompleted, userState);
        }
        
        private void OnGravarEnvioOperationCompleted(object arg) {
            if ((this.GravarEnvioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GravarEnvioCompleted(this, new GravarEnvioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/DCN.WebService.ESocial.GravarRetorno", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoGravarRetorno GravarRetorno(string Guid, ParametroGravarRetorno[] ListaParametroGravarRetorno, string xmlRetorno) {
            object[] results = this.Invoke("GravarRetorno", new object[] {
                        Guid,
                        ListaParametroGravarRetorno,
                        xmlRetorno});
            return ((ResultadoGravarRetorno)(results[0]));
        }
        
        /// <remarks/>
        public void GravarRetornoAsync(string Guid, ParametroGravarRetorno[] ListaParametroGravarRetorno, string xmlRetorno) {
            this.GravarRetornoAsync(Guid, ListaParametroGravarRetorno, xmlRetorno, null);
        }
        
        /// <remarks/>
        public void GravarRetornoAsync(string Guid, ParametroGravarRetorno[] ListaParametroGravarRetorno, string xmlRetorno, object userState) {
            if ((this.GravarRetornoOperationCompleted == null)) {
                this.GravarRetornoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGravarRetornoOperationCompleted);
            }
            this.InvokeAsync("GravarRetorno", new object[] {
                        Guid,
                        ListaParametroGravarRetorno,
                        xmlRetorno}, this.GravarRetornoOperationCompleted, userState);
        }
        
        private void OnGravarRetornoOperationCompleted(object arg) {
            if ((this.GravarRetornoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GravarRetornoCompleted(this, new GravarRetornoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/DCN.WebService.ESocial.ListarEventoPendente", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoEventoPendente ListarEventoPendente(string Guid) {
            object[] results = this.Invoke("ListarEventoPendente", new object[] {
                        Guid});
            return ((ResultadoEventoPendente)(results[0]));
        }
        
        /// <remarks/>
        public void ListarEventoPendenteAsync(string Guid) {
            this.ListarEventoPendenteAsync(Guid, null);
        }
        
        /// <remarks/>
        public void ListarEventoPendenteAsync(string Guid, object userState) {
            if ((this.ListarEventoPendenteOperationCompleted == null)) {
                this.ListarEventoPendenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarEventoPendenteOperationCompleted);
            }
            this.InvokeAsync("ListarEventoPendente", new object[] {
                        Guid}, this.ListarEventoPendenteOperationCompleted, userState);
        }
        
        private void OnListarEventoPendenteOperationCompleted(object arg) {
            if ((this.ListarEventoPendenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarEventoPendenteCompleted(this, new ListarEventoPendenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/DCN.WebService.ESocial.ListarRetornoPendente", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoEventoPendente ListarRetornoPendente(string Guid) {
            object[] results = this.Invoke("ListarRetornoPendente", new object[] {
                        Guid});
            return ((ResultadoEventoPendente)(results[0]));
        }
        
        /// <remarks/>
        public void ListarRetornoPendenteAsync(string Guid) {
            this.ListarRetornoPendenteAsync(Guid, null);
        }
        
        /// <remarks/>
        public void ListarRetornoPendenteAsync(string Guid, object userState) {
            if ((this.ListarRetornoPendenteOperationCompleted == null)) {
                this.ListarRetornoPendenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarRetornoPendenteOperationCompleted);
            }
            this.InvokeAsync("ListarRetornoPendente", new object[] {
                        Guid}, this.ListarRetornoPendenteOperationCompleted, userState);
        }
        
        private void OnListarRetornoPendenteOperationCompleted(object arg) {
            if ((this.ListarRetornoPendenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarRetornoPendenteCompleted(this, new ListarRetornoPendenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ParametroGravarEnvio {
        
        private string cdRespostaField;
        
        private string descRespostaField;
        
        private string dhRecepcaoField;
        
        private string versaoAplicativoRecepcaoField;
        
        private string protocoloEnvioField;
        
        private string[] idsField;
        
        private Ocorrencia[] ocorrenciasField;
        
        private string cNPJTRField;
        
        private string arquivoXMLField;
        
        /// <remarks/>
        public string CdResposta {
            get {
                return this.cdRespostaField;
            }
            set {
                this.cdRespostaField = value;
            }
        }
        
        /// <remarks/>
        public string DescResposta {
            get {
                return this.descRespostaField;
            }
            set {
                this.descRespostaField = value;
            }
        }
        
        /// <remarks/>
        public string DhRecepcao {
            get {
                return this.dhRecepcaoField;
            }
            set {
                this.dhRecepcaoField = value;
            }
        }
        
        /// <remarks/>
        public string VersaoAplicativoRecepcao {
            get {
                return this.versaoAplicativoRecepcaoField;
            }
            set {
                this.versaoAplicativoRecepcaoField = value;
            }
        }
        
        /// <remarks/>
        public string ProtocoloEnvio {
            get {
                return this.protocoloEnvioField;
            }
            set {
                this.protocoloEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("IdsItem")]
        public string[] Ids {
            get {
                return this.idsField;
            }
            set {
                this.idsField = value;
            }
        }
        
        /// <remarks/>
        public Ocorrencia[] Ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJTR {
            get {
                return this.cNPJTRField;
            }
            set {
                this.cNPJTRField = value;
            }
        }
        
        /// <remarks/>
        public string ArquivoXML {
            get {
                return this.arquivoXMLField;
            }
            set {
                this.arquivoXMLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Ocorrencia {
        
        private string codigoField;
        
        private string descricaoField;
        
        private string tipoField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ParametroGravarRetorno {
        
        private string idField;
        
        private string protocoloField;
        
        private string cdRespostaField;
        
        private string descRespostaField;
        
        private string dhProcessamentoField;
        
        private string versaoAplicativoProcessamentoField;
        
        private Ocorrencia[] ocorrenciasField;
        
        private string numeroReciboField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
            }
        }
        
        /// <remarks/>
        public string CdResposta {
            get {
                return this.cdRespostaField;
            }
            set {
                this.cdRespostaField = value;
            }
        }
        
        /// <remarks/>
        public string DescResposta {
            get {
                return this.descRespostaField;
            }
            set {
                this.descRespostaField = value;
            }
        }
        
        /// <remarks/>
        public string DhProcessamento {
            get {
                return this.dhProcessamentoField;
            }
            set {
                this.dhProcessamentoField = value;
            }
        }
        
        /// <remarks/>
        public string VersaoAplicativoProcessamento {
            get {
                return this.versaoAplicativoProcessamentoField;
            }
            set {
                this.versaoAplicativoProcessamentoField = value;
            }
        }
        
        /// <remarks/>
        public Ocorrencia[] Ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroRecibo {
            get {
                return this.numeroReciboField;
            }
            set {
                this.numeroReciboField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class TipoEvento {
        
        private string codigoField;
        
        private string descricaoField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoEventoPendente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoGravarRetorno))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoGravarEnvio))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Resultado {
        
        private bool sucessoField;
        
        private bool sucessoFieldSpecified;
        
        private string mensagemField;
        
        private string divisorLinhaField;
        
        private string tagField;
        
        /// <remarks/>
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SucessoSpecified {
            get {
                return this.sucessoFieldSpecified;
            }
            set {
                this.sucessoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public string DivisorLinha {
            get {
                return this.divisorLinhaField;
            }
            set {
                this.divisorLinhaField = value;
            }
        }
        
        /// <remarks/>
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoEventoPendente : Resultado {
        
        private TipoEvento[] retornoResultadoEventoPendenteField;
        
        /// <remarks/>
        public TipoEvento[] RetornoResultadoEventoPendente {
            get {
                return this.retornoResultadoEventoPendenteField;
            }
            set {
                this.retornoResultadoEventoPendenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoGravarRetorno : Resultado {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoGravarEnvio : Resultado {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GravarEnvioCompletedEventHandler(object sender, GravarEnvioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GravarEnvioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GravarEnvioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoGravarEnvio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoGravarEnvio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GravarRetornoCompletedEventHandler(object sender, GravarRetornoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GravarRetornoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GravarRetornoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoGravarRetorno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoGravarRetorno)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ListarEventoPendenteCompletedEventHandler(object sender, ListarEventoPendenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarEventoPendenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarEventoPendenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoEventoPendente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoEventoPendente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ListarRetornoPendenteCompletedEventHandler(object sender, ListarRetornoPendenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarRetornoPendenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarRetornoPendenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoEventoPendente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoEventoPendente)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591