//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SCI.Corporativo.IRKOMPACTA {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.irko.com.br")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CadastrarCertificadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarCertificadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::SCI.Properties.Settings.Default.SCI_Corporativo_IRKOMPACTA_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CadastrarCertificadoCompletedEventHandler CadastrarCertificadoCompleted;
        
        /// <remarks/>
        public event ListarEmpresaCompletedEventHandler ListarEmpresaCompleted;
        
        /// <remarks/>
        public event RecuperarCertificadoCompletedEventHandler RecuperarCertificadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/ADM.WebService.Corporativo.CadastrarCertificado", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resultado CadastrarCertificado(string Guid, Certificado Certificado) {
            object[] results = this.Invoke("CadastrarCertificado", new object[] {
                        Guid,
                        Certificado});
            return ((Resultado)(results[0]));
        }
        
        /// <remarks/>
        public void CadastrarCertificadoAsync(string Guid, Certificado Certificado) {
            this.CadastrarCertificadoAsync(Guid, Certificado, null);
        }
        
        /// <remarks/>
        public void CadastrarCertificadoAsync(string Guid, Certificado Certificado, object userState) {
            if ((this.CadastrarCertificadoOperationCompleted == null)) {
                this.CadastrarCertificadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarCertificadoOperationCompleted);
            }
            this.InvokeAsync("CadastrarCertificado", new object[] {
                        Guid,
                        Certificado}, this.CadastrarCertificadoOperationCompleted, userState);
        }
        
        private void OnCadastrarCertificadoOperationCompleted(object arg) {
            if ((this.CadastrarCertificadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarCertificadoCompleted(this, new CadastrarCertificadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/ADM.WebService.Corporativo.ListarEmpresa", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoListarEmpresa ListarEmpresa(string Guid) {
            object[] results = this.Invoke("ListarEmpresa", new object[] {
                        Guid});
            return ((ResultadoListarEmpresa)(results[0]));
        }
        
        /// <remarks/>
        public void ListarEmpresaAsync(string Guid) {
            this.ListarEmpresaAsync(Guid, null);
        }
        
        /// <remarks/>
        public void ListarEmpresaAsync(string Guid, object userState) {
            if ((this.ListarEmpresaOperationCompleted == null)) {
                this.ListarEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarEmpresaOperationCompleted);
            }
            this.InvokeAsync("ListarEmpresa", new object[] {
                        Guid}, this.ListarEmpresaOperationCompleted, userState);
        }
        
        private void OnListarEmpresaOperationCompleted(object arg) {
            if ((this.ListarEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarEmpresaCompleted(this, new ListarEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irko.com.br/ADM.WebService.Corporativo.RecuperarCertificado", RequestNamespace="http://www.irko.com.br", ResponseNamespace="http://www.irko.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoRecuperarCertificado RecuperarCertificado(string Guid, string CNPJCPF) {
            object[] results = this.Invoke("RecuperarCertificado", new object[] {
                        Guid,
                        CNPJCPF});
            return ((ResultadoRecuperarCertificado)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarCertificadoAsync(string Guid, string CNPJCPF) {
            this.RecuperarCertificadoAsync(Guid, CNPJCPF, null);
        }
        
        /// <remarks/>
        public void RecuperarCertificadoAsync(string Guid, string CNPJCPF, object userState) {
            if ((this.RecuperarCertificadoOperationCompleted == null)) {
                this.RecuperarCertificadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarCertificadoOperationCompleted);
            }
            this.InvokeAsync("RecuperarCertificado", new object[] {
                        Guid,
                        CNPJCPF}, this.RecuperarCertificadoOperationCompleted, userState);
        }
        
        private void OnRecuperarCertificadoOperationCompleted(object arg) {
            if ((this.RecuperarCertificadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarCertificadoCompleted(this, new RecuperarCertificadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Certificado {
        
        private string aliasField;
        
        private string ownerListField;
        
        private byte[] certificateField;
        
        private CertificadoPrivateKeyType privateKeyTypeField;
        
        private byte[] privateKeyField;
        
        private string privateKeyPasswordField;
        
        private string cAFileField;
        
        private string peerNamesField;
        
        private byte[] subjectKeyIdentifierField;
        
        private byte[] thumbprintField;
        
        private string serialNumberField;
        
        private string issuerDNField;
        
        private string subjectDNField;
        
        private System.DateTime validityNotBeforeField;
        
        private bool validityNotBeforeFieldSpecified;
        
        private System.DateTime validityNotAfterField;
        
        private bool validityNotAfterFieldSpecified;
        
        private string cNPJCPFField;
        
        private byte[] pfxFileField;
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string OwnerList {
            get {
                return this.ownerListField;
            }
            set {
                this.ownerListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Certificate {
            get {
                return this.certificateField;
            }
            set {
                this.certificateField = value;
            }
        }
        
        /// <remarks/>
        public CertificadoPrivateKeyType PrivateKeyType {
            get {
                return this.privateKeyTypeField;
            }
            set {
                this.privateKeyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PrivateKey {
            get {
                return this.privateKeyField;
            }
            set {
                this.privateKeyField = value;
            }
        }
        
        /// <remarks/>
        public string PrivateKeyPassword {
            get {
                return this.privateKeyPasswordField;
            }
            set {
                this.privateKeyPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string CAFile {
            get {
                return this.cAFileField;
            }
            set {
                this.cAFileField = value;
            }
        }
        
        /// <remarks/>
        public string PeerNames {
            get {
                return this.peerNamesField;
            }
            set {
                this.peerNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SubjectKeyIdentifier {
            get {
                return this.subjectKeyIdentifierField;
            }
            set {
                this.subjectKeyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Thumbprint {
            get {
                return this.thumbprintField;
            }
            set {
                this.thumbprintField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string IssuerDN {
            get {
                return this.issuerDNField;
            }
            set {
                this.issuerDNField = value;
            }
        }
        
        /// <remarks/>
        public string SubjectDN {
            get {
                return this.subjectDNField;
            }
            set {
                this.subjectDNField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidityNotBefore {
            get {
                return this.validityNotBeforeField;
            }
            set {
                this.validityNotBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidityNotBeforeSpecified {
            get {
                return this.validityNotBeforeFieldSpecified;
            }
            set {
                this.validityNotBeforeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidityNotAfter {
            get {
                return this.validityNotAfterField;
            }
            set {
                this.validityNotAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidityNotAfterSpecified {
            get {
                return this.validityNotAfterFieldSpecified;
            }
            set {
                this.validityNotAfterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CNPJCPF {
            get {
                return this.cNPJCPFField;
            }
            set {
                this.cNPJCPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PfxFile {
            get {
                return this.pfxFileField;
            }
            set {
                this.pfxFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.irko.com.br")]
    public enum CertificadoPrivateKeyType {
        
        /// <remarks/>
        RSA,
        
        /// <remarks/>
        DSA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Chamado {
        
        private string aNOMESField;
        
        private string nomeField;
        
        private string totalChamadoField;
        
        private string fechadoField;
        
        private string naoProcedeField;
        
        private string pendenteField;
        
        /// <remarks/>
        public string ANOMES {
            get {
                return this.aNOMESField;
            }
            set {
                this.aNOMESField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string TotalChamado {
            get {
                return this.totalChamadoField;
            }
            set {
                this.totalChamadoField = value;
            }
        }
        
        /// <remarks/>
        public string Fechado {
            get {
                return this.fechadoField;
            }
            set {
                this.fechadoField = value;
            }
        }
        
        /// <remarks/>
        public string NaoProcede {
            get {
                return this.naoProcedeField;
            }
            set {
                this.naoProcedeField = value;
            }
        }
        
        /// <remarks/>
        public string Pendente {
            get {
                return this.pendenteField;
            }
            set {
                this.pendenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class PairOfRotinaSistemaIrkoKeyLong {
        
        private string rotinaSistemaIrkoKeyField;
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RotinaSistemaIrkoKey {
            get {
                return this.rotinaSistemaIrkoKeyField;
            }
            set {
                this.rotinaSistemaIrkoKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public long Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Painel {
        
        private long totalLincencaField;
        
        private bool totalLincencaFieldSpecified;
        
        private long usoAtualLicencaField;
        
        private bool usoAtualLicencaFieldSpecified;
        
        private long totalLogadoIrkoField;
        
        private bool totalLogadoIrkoFieldSpecified;
        
        private PairOfRotinaSistemaIrkoKeyLong[] rotinaSistemaIrkoField;
        
        private long tamanhoLockField;
        
        private bool tamanhoLockFieldSpecified;
        
        private long usoLockField;
        
        private bool usoLockFieldSpecified;
        
        private long lockLivreField;
        
        private bool lockLivreFieldSpecified;
        
        private long lockSistemaField;
        
        private bool lockSistemaFieldSpecified;
        
        private long workUsadoField;
        
        private bool workUsadoFieldSpecified;
        
        private Chamado[] chamadosField;
        
        /// <remarks/>
        public long TotalLincenca {
            get {
                return this.totalLincencaField;
            }
            set {
                this.totalLincencaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalLincencaSpecified {
            get {
                return this.totalLincencaFieldSpecified;
            }
            set {
                this.totalLincencaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long UsoAtualLicenca {
            get {
                return this.usoAtualLicencaField;
            }
            set {
                this.usoAtualLicencaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UsoAtualLicencaSpecified {
            get {
                return this.usoAtualLicencaFieldSpecified;
            }
            set {
                this.usoAtualLicencaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long TotalLogadoIrko {
            get {
                return this.totalLogadoIrkoField;
            }
            set {
                this.totalLogadoIrkoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalLogadoIrkoSpecified {
            get {
                return this.totalLogadoIrkoFieldSpecified;
            }
            set {
                this.totalLogadoIrkoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RotinaSistemaIrkoItem")]
        public PairOfRotinaSistemaIrkoKeyLong[] RotinaSistemaIrko {
            get {
                return this.rotinaSistemaIrkoField;
            }
            set {
                this.rotinaSistemaIrkoField = value;
            }
        }
        
        /// <remarks/>
        public long TamanhoLock {
            get {
                return this.tamanhoLockField;
            }
            set {
                this.tamanhoLockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TamanhoLockSpecified {
            get {
                return this.tamanhoLockFieldSpecified;
            }
            set {
                this.tamanhoLockFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long UsoLock {
            get {
                return this.usoLockField;
            }
            set {
                this.usoLockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UsoLockSpecified {
            get {
                return this.usoLockFieldSpecified;
            }
            set {
                this.usoLockFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long LockLivre {
            get {
                return this.lockLivreField;
            }
            set {
                this.lockLivreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LockLivreSpecified {
            get {
                return this.lockLivreFieldSpecified;
            }
            set {
                this.lockLivreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long LockSistema {
            get {
                return this.lockSistemaField;
            }
            set {
                this.lockSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LockSistemaSpecified {
            get {
                return this.lockSistemaFieldSpecified;
            }
            set {
                this.lockSistemaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long WorkUsado {
            get {
                return this.workUsadoField;
            }
            set {
                this.workUsadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WorkUsadoSpecified {
            get {
                return this.workUsadoFieldSpecified;
            }
            set {
                this.workUsadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Chamado[] Chamados {
            get {
                return this.chamadosField;
            }
            set {
                this.chamadosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Idioma {
        
        private string codigoField;
        
        private string descricaoField;
        
        private bool habilitadoField;
        
        private bool habilitadoFieldSpecified;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public bool Habilitado {
            get {
                return this.habilitadoField;
            }
            set {
                this.habilitadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HabilitadoSpecified {
            get {
                return this.habilitadoFieldSpecified;
            }
            set {
                this.habilitadoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Empresa {
        
        private long codigoField;
        
        private string razaoSocialField;
        
        private string cNPJCPFField;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        public long Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string RazaoSocial {
            get {
                return this.razaoSocialField;
            }
            set {
                this.razaoSocialField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJCPF {
            get {
                return this.cNPJCPFField;
            }
            set {
                this.cNPJCPFField = value;
            }
        }
        
        /// <remarks/>
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Menu {
        
        private Menu[] menusInferioresField;
        
        private string menu1Field;
        
        private string descricaoField;
        
        private MenuTipo tipoField;
        
        private MenuStatus statusField;
        
        private string namespaceField;
        
        private string programaField;
        
        private MenuBloqueio bloqueioField;
        
        private bool bloqueioFieldSpecified;
        
        private bool permiteTrocaEmpresaField;
        
        private bool permiteTrocaEmpresaFieldSpecified;
        
        private bool permiteMultiTelaField;
        
        private bool permiteMultiTelaFieldSpecified;
        
        private string opcaoMenuCOSField;
        
        private bool permiteEditarField;
        
        private bool permiteEditarFieldSpecified;
        
        /// <remarks/>
        public Menu[] MenusInferiores {
            get {
                return this.menusInferioresField;
            }
            set {
                this.menusInferioresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Menu")]
        public string Menu1 {
            get {
                return this.menu1Field;
            }
            set {
                this.menu1Field = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public MenuTipo Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public MenuStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        public string Programa {
            get {
                return this.programaField;
            }
            set {
                this.programaField = value;
            }
        }
        
        /// <remarks/>
        public MenuBloqueio Bloqueio {
            get {
                return this.bloqueioField;
            }
            set {
                this.bloqueioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BloqueioSpecified {
            get {
                return this.bloqueioFieldSpecified;
            }
            set {
                this.bloqueioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool PermiteTrocaEmpresa {
            get {
                return this.permiteTrocaEmpresaField;
            }
            set {
                this.permiteTrocaEmpresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PermiteTrocaEmpresaSpecified {
            get {
                return this.permiteTrocaEmpresaFieldSpecified;
            }
            set {
                this.permiteTrocaEmpresaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool PermiteMultiTela {
            get {
                return this.permiteMultiTelaField;
            }
            set {
                this.permiteMultiTelaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PermiteMultiTelaSpecified {
            get {
                return this.permiteMultiTelaFieldSpecified;
            }
            set {
                this.permiteMultiTelaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string OpcaoMenuCOS {
            get {
                return this.opcaoMenuCOSField;
            }
            set {
                this.opcaoMenuCOSField = value;
            }
        }
        
        /// <remarks/>
        public bool PermiteEditar {
            get {
                return this.permiteEditarField;
            }
            set {
                this.permiteEditarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PermiteEditarSpecified {
            get {
                return this.permiteEditarFieldSpecified;
            }
            set {
                this.permiteEditarFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.irko.com.br")]
    public enum MenuTipo {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.irko.com.br")]
    public enum MenuStatus {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.irko.com.br")]
    public enum MenuBloqueio {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Usuario {
        
        private long codigoField;
        
        private System.DateTime dataInicioField;
        
        private string nomeField;
        
        private string senhaField;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        public long Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataInicio {
            get {
                return this.dataInicioField;
            }
            set {
                this.dataInicioField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoPainel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoListarIdioma))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoCampo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoRecuperarCertificado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoListarEmpresa))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoMontarMenu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoLogin))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class Resultado {
        
        private bool sucessoField;
        
        private bool sucessoFieldSpecified;
        
        private string mensagemField;
        
        private string divisorLinhaField;
        
        private string tagField;
        
        /// <remarks/>
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SucessoSpecified {
            get {
                return this.sucessoFieldSpecified;
            }
            set {
                this.sucessoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public string DivisorLinha {
            get {
                return this.divisorLinhaField;
            }
            set {
                this.divisorLinhaField = value;
            }
        }
        
        /// <remarks/>
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoPainel : Resultado {
        
        private Painel retornoPainelField;
        
        /// <remarks/>
        public Painel RetornoPainel {
            get {
                return this.retornoPainelField;
            }
            set {
                this.retornoPainelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoListarIdioma : Resultado {
        
        private Idioma[] retornoListarIdiomaField;
        
        /// <remarks/>
        public Idioma[] RetornoListarIdioma {
            get {
                return this.retornoListarIdiomaField;
            }
            set {
                this.retornoListarIdiomaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoCampo : Resultado {
        
        private string retornoCampoField;
        
        /// <remarks/>
        public string RetornoCampo {
            get {
                return this.retornoCampoField;
            }
            set {
                this.retornoCampoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoRecuperarCertificado : Resultado {
        
        private Certificado retornoRecuperarCertificadoField;
        
        /// <remarks/>
        public Certificado RetornoRecuperarCertificado {
            get {
                return this.retornoRecuperarCertificadoField;
            }
            set {
                this.retornoRecuperarCertificadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoListarEmpresa : Resultado {
        
        private Empresa[] retornoListarEmpresaField;
        
        /// <remarks/>
        public Empresa[] RetornoListarEmpresa {
            get {
                return this.retornoListarEmpresaField;
            }
            set {
                this.retornoListarEmpresaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoMontarMenu : Resultado {
        
        private Menu[] retornoResultadoMontarMenuField;
        
        /// <remarks/>
        public Menu[] RetornoResultadoMontarMenu {
            get {
                return this.retornoResultadoMontarMenuField;
            }
            set {
                this.retornoResultadoMontarMenuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irko.com.br")]
    public partial class ResultadoLogin : Resultado {
        
        private Usuario retornoResultadoLoginField;
        
        /// <remarks/>
        public Usuario RetornoResultadoLogin {
            get {
                return this.retornoResultadoLoginField;
            }
            set {
                this.retornoResultadoLoginField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CadastrarCertificadoCompletedEventHandler(object sender, CadastrarCertificadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastrarCertificadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastrarCertificadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarEmpresaCompletedEventHandler(object sender, ListarEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoListarEmpresa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoListarEmpresa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RecuperarCertificadoCompletedEventHandler(object sender, RecuperarCertificadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarCertificadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarCertificadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoRecuperarCertificado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoRecuperarCertificado)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591